# Generated by Django 4.2.1 on 2023-06-09 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("contact", models.CharField(max_length=10, null=True)),
                ("address", models.CharField(max_length=250, null=True)),
                ("age", models.CharField(max_length=3, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tripdate", models.CharField(max_length=100, null=True)),
                ("ttype", models.CharField(max_length=100, null=True)),
                ("pickup", models.CharField(max_length=100, null=True)),
                ("dropoff", models.CharField(max_length=100, null=True)),
                ("pickuptime", models.DateTimeField(max_length=100, null=True)),
                ("dropofftime", models.DateTimeField(max_length=100, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("Active", "Active"),
                            ("Complete", "Complete"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="server.customer",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="server.driver",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Customers",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="createdAt",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="customerid",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="driverid",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="dropoff",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="dropofftime",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="pickup",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="pickuptime",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="tripdate",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="ttype",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="vehicleid",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="veh_location",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="veh_make",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="veh_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="veh_number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="server.vehicle",
            ),
        ),
    ]
