# Generated by Django 4.2.2 on 2023-06-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0004_trip_fullcapacity_alter_trip_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="dropofftime",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="fullcapacity",
            field=models.BooleanField(
                choices=[(True, "True"), (False, "False")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="pickuptime",
            field=models.TimeField(null=True),
        ),
    ]
