# Generated by Django 4.2.2 on 2023-06-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0005_alter_trip_dropofftime_alter_trip_fullcapacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="trip_number",
            field=models.CharField(default="DEFAULT_VALUE_HERE", max_length=20),
        ),
    ]
