# Generated by Django 4.2.2 on 2023-07-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0007_remove_trip_trip_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="fullcapacity",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fullcapacity",
            field=models.BooleanField(
                choices=[(True, "True"), (False, "False")], null=True
            ),
        ),
    ]
