# Generated by Django 4.2.2 on 2023-07-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0008_remove_trip_fullcapacity_vehicle_fullcapacity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="dropoff",
            new_name="dropoffaddress",
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="pickup",
            new_name="dropoffgeocode",
        ),
        migrations.AddField(
            model_name="trip",
            name="pickupaddress",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="pickupgeocode",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
