# Generated by Django 4.2.2 on 2023-07-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0009_rename_dropoff_trip_dropoffaddress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="stops",
            field=models.JSONField(null=True),
        ),
    ]
