# Generated by Django 4.2.2 on 2023-07-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0010_trip_stops"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("Arriving", "Arriving"),
                    ("Ongoing", "Ongoing"),
                    ("Complete", "Complete"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="veh_location",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
